DROP DATABASE IF EXISTS pokeBBDD;

CREATE DATABASE pokeBBDD;
USE pokeBBDD;

CREATE TABLE pokemons(
    NUMERO TINYINT UNSIGNED NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    NOMBRE2 VARCHAR(20) NOT NULL,
    TIPO1 VARCHAR(20) NOT NULL,
    TIPO2 VARCHAR(20),
    IMG VARCHAR(30) NOT NULL,
    PRIMARY KEY (NUMERO)
);

